/**
 * scripts/design-states.cjs
 *
 * Machine-readable codification of the 14 design states defined in
 * docs/deepseek/01-design-contract.md.
 *
 * Every state object MUST contain:
 *   id                — "D01" … "D14"
 *   name              — kebab-case identifier matching the reference PNG stem
 *   viewport          — { width, height } in CSS pixels
 *   reference         — relative path to the reference PNG
 *   driver            — how the product reaches this state (used by e2e-design-14.cjs)
 *   geometry          — hard-asserted dimensions from the design contract
 *   masks             — array of { x, y, width, height } regions excluded from pixel diff
 *   maxMismatchRatio  — upper bound for pixel mismatch (<= 0.015)
 *
 * Dark states (D03, D12, D14) additionally carry:
 *   theme                — "dark"
 *   sourceRootCorrection — true (original HTML erroneously declares light)
 *
 * The source HTML file for each state is resolved via `sourceFile`.
 */

const STATES = [
  {
    id: "D01",
    name: "empty-workspace",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/01-empty-workspace.png",
    sourceFile: "空状态欢迎页.html",
    driver: "empty",
    geometry: {
      topbar: 56,
      source: 280,
      inspector: 320,
      statusbar: 28,
      stagePadding: 24,
      previewWidth: 800,
      urlBarHeight: 32,
      illustrationArea: { width: 200, height: 160 },
      illustrationGraphic: { width: 80, height: 96 },
      ctaHeight: 36,
      ctaGap: 28,
      pasteLinkGap: 14,
      descriptionMaxWidth: 420,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D02",
    name: "workspace-light",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/02-workspace-light.png",
    sourceFile: "主工作区 (亮).html",
    driver: "workspace-light",
    geometry: {
      topbar: 56,
      source: 280,
      inspector: 320,
      statusbar: 28,
      stagePadding: 24,
      previewWidth: 800,
      previewMinHeight: 456,
      urlBarHeight: 32,
      sourceLineNumberColumn: 36,
      sourceStatusBar: 28,
      inspectorCardMargin: 8,
      inspectorActiveIndicator: 3,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D03",
    name: "workspace-dark",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/03-workspace-dark.png",
    sourceFile: "主工作区 (暗).html",
    driver: "workspace-dark",
    theme: "dark",
    sourceRootCorrection: true,
    geometry: {
      topbar: 56,
      source: 280,
      inspector: 320,
      statusbar: 28,
      stagePadding: 24,
      previewWidth: 800,
      previewMinHeight: 456,
      urlBarHeight: 32,
      sourceLineNumberColumn: 36,
      sourceStatusBar: 28,
      inspectorCardMargin: 8,
      inspectorActiveIndicator: 3,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D04",
    name: "dom-tree",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/04-dom-tree.png",
    sourceFile: "DOM 树面板.html",
    driver: "dom-tree",
    geometry: {
      topbar: 56,
      source: 280,
      inspector: 320,
      statusbar: 28,
      searchHeight: 28,
      treeRowHeight: 24,
      treeIndent: 16,
      selectedIndicator: 3,
      canvasOutlineWidth: 2,
      canvasOutlineOffset: -2,
      canvasLabelOffset: -20,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D05",
    name: "device-viewports",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/05-device-viewports.png",
    sourceFile: "手机_平板视口.html",
    driver: "device-preview",
    geometry: {
      topbar: 56,
      sideRail: 48,
      titleArea: 220,
      deviceFrame: { width: 399, height: 691, radius: 36, padding: 12 },
      deviceScreen: { width: 375, height: 667, radius: 24 },
      notch: { size: 24, z: 10 },
      statusBar: { height: 20, z: 5 },
      mobileNav: { height: 44 },
      dimensionToolbar: { height: 32 },
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D06",
    name: "mobile-drawer",
    viewport: { width: 390, height: 844 },
    reference: "docs/design-references/06-mobile-drawer.png",
    sourceFile: "移动端抽屉布局.html",
    driver: "mobile-drawer",
    geometry: {
      statusHeight: 44,
      header: 52,
      bottomNav: 52,
      canvasPadding: { top: 20, right: 16, bottom: 16, left: 16 },
      previewWidth: 340,
      backdrop: { color: "rgba(0,0,0,0.40)", z: 40 },
      drawer: { width: 320, z: 50 },
      drawerHeader: 52,
      drawerTab: 40,
      drawerStatus: 28,
      homeIndicator: { width: 134, height: 5, bottom: 6, opacity: 0.3, z: 60 },
      transitionDuration: { min: 180, max: 240 },
      minTouchTarget: 32,
      preferredTouchTarget: 40,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D07",
    name: "color-picker",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/07-color-picker.png",
    sourceFile: "颜色选择器弹层.html",
    driver: "color-picker",
    geometry: {
      trigger: { top: 220, left: 1116, z: 50 },
      popover: { top: 257, right: 16, width: 300, padding: 16, radius: 6, z: 100 },
      currentColor: "#37352f",
      hexInput: { width: 80, height: 28 },
      saturationMap: { width: 268, height: 140 },
      referenceGrid: { cols: 12, rows: 7, gap: 1 },
      hueSlider: { width: 268, height: 8, thumb: 14 },
      alphaSlider: { width: 268, height: 8, thumb: 14 },
      presets: { cols: 8, swatch: 24, gap: 4, count: 16 },
      recent: { cols: 8, swatch: 20, filled: 5, empty: 3 },
      selectedSwatch: { outline: 2, offset: 1 },
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D08",
    name: "dropdown-menu",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/08-dropdown-menu.png",
    sourceFile: "下拉菜单_菜单.html",
    driver: "menu-showcase",
    geometry: {
      menuPadding: 4,
      menuRadius: 5,
      itemHeight: 32,
      itemPaddingX: 12,
      itemGap: 8,
      separatorHeight: 1,
      separatorMargin: { y: 4, x: 8 },
      fileMenu: { top: 52, left: 40, width: 220 },
      contextMenu: { top: 400, left: 620, width: 200 },
      viewportMenu: { top: 52, right: 40, width: 180 },
      providerMenu: { bottom: 52, right: 40, width: 240 },
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D09",
    name: "toast-tooltip",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/09-toast-tooltip.png",
    sourceFile: "Toast + Tooltip 组件.html",
    driver: "toast-tooltip",
    geometry: {
      showcasePadding: { x: 64, y: 48 },
      sectionGap: 36,
      tooltip: { z: 110, fontSize: 11, padding: { x: 8, y: 4 } },
      toastRegion: { bottom: 24, right: 24, gap: 8, z: 120 },
      toast: { width: 320, minHeight: 40, padding: 12 },
      buttonHeight: 32,
      iconOnlyButton: 28,
      inputHeight: 32,
      checkbox: 16,
      toggle: { width: 28, height: 16, thumb: 12 },
      chip: 22,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D10",
    name: "diagnostics-error",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/10-diagnostics-error.png",
    sourceFile: "诊断_错误面板.html",
    driver: "diagnostics",
    geometry: {
      topbar: 56,
      source: 280,
      inspector: 320,
      statusbar: 28,
      previewWidth: 800,
      previewMinHeight: 424,
      bottomBar: 32,
      topbarProblemBackground: "rgba(203,145,47,0.08)",
      topbarProblemBorderAlpha: 0.20,
      canvasOutlineWidth: 2,
      canvasLabelOffset: -18,
      errorRowBackground: "rgba(224,62,62,0.06)",
      warningRowBackground: "rgba(203,145,47,0.05)",
      fixture: { errors: 1, warnings: 1, infos: 1 },
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D11",
    name: "export-light",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/11-export-light.png",
    sourceFile: "导出预览 (亮).html",
    driver: "export-light",
    geometry: {
      dialogWidth: 680,
      dialogRadius: 6,
      header: 48,
      tabs: 40,
      preview: 360,
      options: 44,
      footer: 48,
      previewMargin: 24,
      closeButton: 28,
      primaryButton: { height: 32, minWidth: 80 },
      backdrop: "rgba(15,15,15,0.30)",
      workspaceOpacity: 0.35,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D12",
    name: "export-dark",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/12-export-dark.png",
    sourceFile: "导出预览 (暗).html",
    driver: "export-dark",
    theme: "dark",
    sourceRootCorrection: true,
    geometry: {
      dialogWidth: 680,
      dialogRadius: 6,
      header: 48,
      tabs: 40,
      preview: 360,
      options: 44,
      footer: 48,
      previewMargin: 24,
      closeButton: 28,
      primaryButton: { height: 32, minWidth: 80 },
      backdrop: "rgba(0,0,0,0.60)",
      workspaceOpacity: 0.35,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D13",
    name: "history-light",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/13-history-light.png",
    sourceFile: "历史记录 (亮).html",
    driver: "history-light",
    geometry: {
      panelTop: 76,
      panelRight: 16,
      panelWidth: 340,
      panelMaxHeight: 808,
      panelRadius: 8,
      rowHeight: 56,
      currentIndicator: 3,
      typePill: { height: 28, radius: 14 },
      timeFontSize: 11,
      dateFontSize: 10,
      titleFontSize: 13,
      footer: 40,
      scrollbar: 4,
      backdrop: "rgba(15,15,15,0.25)",
      workspaceOpacity: 0.45,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
  {
    id: "D14",
    name: "history-dark",
    viewport: { width: 1440, height: 900 },
    reference: "docs/design-references/14-history-dark.png",
    sourceFile: "历史记录 (暗).html",
    driver: "history-dark",
    theme: "dark",
    sourceRootCorrection: true,
    geometry: {
      panelTop: 76,
      panelRight: 16,
      panelWidth: 340,
      panelMaxHeight: 808,
      panelRadius: 8,
      rowHeight: 56,
      currentIndicator: 3,
      typePill: { height: 28, radius: 14 },
      timeFontSize: 11,
      dateFontSize: 10,
      titleFontSize: 13,
      footer: 40,
      scrollbar: 4,
      backdrop: "rgba(0,0,0,0.60)",
      workspaceOpacity: 0.45,
    },
    masks: [],
    maxMismatchRatio: 0.015,
  },
];

function getState(id) {
  const s = STATES.find((st) => st.id === id);
  if (!s) throw new Error(`Unknown design state: ${id}`);
  return s;
}

module.exports = { states: STATES, getState };
